src/Entity/Eleve.php
<?php

namespace App\Entity;

use App\Repository\EleveRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EleveRepository::class)
 */
class Eleve
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $prenom;


    /**
     * @ORM\Column(type="string", length=5)
     */
    private $promotion;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="ideleves")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Admin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tuteur;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $Specialite;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="eleves")
     */
    private $Enseignant;

    /**
     * @ORM\OneToMany(targetEntity=Cappfpmp::class, mappedBy="etudiant", cascade={"persist"})
     */
    private $cappfpmps;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $Classe;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Formation;

    public function __construct()
    {
        $this->cappfpmps = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getClasse(): ?string
    {
        return $this->Classe;
    }

    public function setClasse(string $classe): self
    {
        $this->Classe = $classe;

        return $this;
    }

    public function getPromotion(): ?string
    {
        return $this->promotion;
    }

    public function setPromotion(string $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    public function getAdmin(): ?utilisateur
    {
        return $this->Admin;
    }

    public function setAdmin(?utilisateur $Admin): self
    {
        $this->Admin = $Admin;

        return $this;
    }

    public function getTuteur(): ?string
    {
        return $this->tuteur;
    }

    public function setTuteur(string $tuteur): self
    {
        $this->tuteur = $tuteur;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->Specialite;
    }

    public function setSpecialite(?string $Specialite): self
    {
        $this->Specialite = $Specialite;

        return $this;
    }

    public function getFormation(): ?string
    {
        return $this->Formation;
    }

    public function setFormation(?string $Formation): self
    {
        $this->Formation = $Formation;

        return $this;
    }

    public function getEnseignant(): ?Utilisateur
    {
        return $this->Enseignant;
    }

    public function setEnseignant(?Utilisateur $Enseignant): self
    {
        $this->Enseignant = $Enseignant;

        return $this;
    }

    /**
     * @return Collection<int, Cappfpmp>
     */
    public function getCappfpmps(): Collection
    {
        return $this->cappfpmps;
    }

    public function addCappfpmp(Cappfpmp $cappfpmp): self
    {
        if (!$this->cappfpmps->contains($cappfpmp)) {
            $this->cappfpmps[] = $cappfpmp;
            $cappfpmp->setEtudiant($this);
        }

        return $this;
    }

    public function removeCappfpmp(Cappfpmp $cappfpmp): self
    {
        if ($this->cappfpmps->removeElement($cappfpmp)) {
            // set the owning side to null (unless already changed)
            if ($cappfpmp->getEtudiant() === $this) {
                $cappfpmp->setEtudiant(null);
            }
        }

        return $this;
    }

    
}

src/Controller/AdministrateurController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\RegistrationFormType;
use App\Form\ChangementmdpType;
use App\Form\AffecterenseigantType;
use App\Form\EleveType;
use App\Entity\Eleve;
use App\Entity\Ligne;
use App\Entity\Sousligne;
use App\Entity\Cappfpmp;
use App\Entity\Travail;
use App\Entity\Competence;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;    
use Symfony\Contracts\Translation\TranslatorInterface;

class AdministrateurController extends AbstractController
{
    /**
     * @Route("/admin", name="admin_home")
     */
    public function index(): Response
    {
        return $this->render('administrateur/index.html.twig', [
            'controller_name' => 'AdministrateurController',
        ]);
    }
    /**
     * @Route("/admin/listeadmin", name="app_administrateur_liste")
     */
    public function liste(): Response
    {
     
        $repository = $this->getDoctrine()->getRepository( Utilisateur::class);
        $Admins = $repository->findBy(['type'=>'Admin']);
       return $this->render('administrateur/liste.html.twig', [
            'controller_name' => 'AdminController',
            "Admins" => $Admins,
            'type' => 'Administrateur'
        ]);
    
    }
    /**
     * @Route("/admin/nouveladmin", name="newteacher")
     */
    public function new(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    { $user = new Utilisateur();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
            $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $user->setRoles(["ROLE_ADMIN"]);
            $user->setType("Admin");
            $entityManager->persist($user);
            $entityManager->flush();
            // do anything else you need here, like send an email

            return $this->redirectToRoute('admin_home');
        }

        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form->createView(),
            'type' => 'Administrateur'
        ]);
    }
    /**
     * @Route("/admin/listeenseignants", name="adminListeEnseignant")
     */
    public function teachers(): Response
    
    {
        $repository = $this->getDoctrine()->getRepository( Utilisateur::class);
        $Admins = $repository->findBy(['type'=>'Enseignant']);
       
        return $this->render('administrateur/liste.html.twig', [
            'controller_name' => 'AdminController',
            "Admins" => $Admins,
            'type' => 'Enseignant'
        ]);
    }
       /**
     * @Route("/admin/nouvelenseignant", name="new_teacher")
     */
    public function newteacher(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
        $user = new Utilisateur();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
            $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            
            );
            $user->setRoles(["ROLE_ENSEIGNANT"]);
            $user->setType("Enseignant");
             $entityManager->persist($user);
            $entityManager->flush();
            // do anything else you need here, like send an email

            return $this->redirectToRoute('admin_home');
        }

        return $this->render('enseignants/new.html.twig', [
            'registrationForm' => $form->createView(),
            'type' => 'Enseignant'
        ]);
    }
    /**
     * @Route("/admin/compte", name="admincompte")
     */
    public function compte(): Response
    
    {
        return $this->render('administrateur/moncompte.html.twig', []);

    }
    /**
     * @Route("/admin/{id}/changermdp", name="adminmdp")
     */
    public function changementmdp(Utilisateur $user, Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    
    {
        $form = $this->createForm(ChangementmdpType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
            $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            
            );
             $entityManager->persist($user);
            $entityManager->flush();
            // do anything else you need here, like send an email

            return $this->redirectToRoute('admin_home');
        }

        return $this->render('registration/changementmdp.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
        return $this->render('administrateur/moncompte.html.twig', []);

    }
      /**
     * @Route("/admin/listeeleves", name="listeeleves")
     */
    public function students(): Response
    
    {
        $repository = $this->getDoctrine()->getRepository( Eleve::class);
        $Eleves = $repository->findAll();
       
        return $this->render('administrateur/listeeleves.html.twig', [
            "Eleves" => $Eleves,
        ]);
    }
   
    /**
     * @Route("/admin/neweleveCAP", name="newstudentcap")
     */
    public function newstudent(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    
    { $eleve=new ELeve();
        $pfmp1=new CAppfpmp();$pfmp1->setNumero(1);
        $pfmp2=new CAppfpmp();$pfmp2->setNumero(2);
        $pfmp3=new CAppfpmp();$pfmp3->setNumero(3);
        $pfmp4=new CAppfpmp();$pfmp4->setNumero(4);
        $ligne11=new  ligne();
        $ligne12=new  ligne();
        $ligne13=new  ligne();
        $ligne14=new  ligne();
        $ligne21=new  ligne();
        $ligne22=new  ligne();
        $ligne23=new  ligne();
        $ligne24=new  ligne();
        $ligne31=new  ligne();
        $ligne32=new  ligne();
        $ligne33=new  ligne();
        $ligne34=new  ligne();
        $ligne41=new  ligne();
        $ligne42=new  ligne();
        $ligne43=new  ligne();
        $ligne44=new  ligne();
        $repository = $this->getDoctrine()->getRepository( Competence::class);
        $competence=$repository->findBy(['id'=>'1']);
        $ligne11->setCompetence($repository->findBy(['id'=>'1'])[0]);
        $ligne12->setCompetence($repository->findBy(['id'=>'2'])[0]);
        $ligne13->setCompetence($repository->findBy(['id'=>'3'])[0]);
        $ligne14->setCompetence($repository->findBy(['id'=>'4'])[0]);
        $ligne21->setCompetence($repository->findBy(['id'=>'1'])[0]);
        $ligne22->setCompetence($repository->findBy(['id'=>'2'])[0]);
        $ligne23->setCompetence($repository->findBy(['id'=>'3'])[0]);
        $ligne24->setCompetence($repository->findBy(['id'=>'4'])[0]);
        $ligne31->setCompetence($repository->findBy(['id'=>'1'])[0]);
        $ligne32->setCompetence($repository->findBy(['id'=>'2'])[0]);
        $ligne33->setCompetence($repository->findBy(['id'=>'3'])[0]);
        $ligne34->setCompetence($repository->findBy(['id'=>'4'])[0]);
        $ligne41->setCompetence($repository->findBy(['id'=>'1'])[0]);
        $ligne42->setCompetence($repository->findBy(['id'=>'2'])[0]);
        $ligne43->setCompetence($repository->findBy(['id'=>'3'])[0]);
        $ligne44->setCompetence($repository->findBy(['id'=>'4'])[0]);

        $sousligne11=new  Sousligne();
        $sousligne12=new  Sousligne();
        $sousligne13=new  Sousligne();
        $sousligne14=new  Sousligne();
        $sousligne15=new  Sousligne();
        $sousligne16=new  Sousligne();
        $sousligne17=new  Sousligne();
        $sousligne18=new  Sousligne();
        $sousligne19=new  Sousligne();
        $sousligne110=new  Sousligne();
        $sousligne111=new  Sousligne();
        $sousligne112=new  Sousligne();
        $sousligne113=new  Sousligne();
        $sousligne114=new  Sousligne();
        $sousligne115=new  Sousligne();
        $sousligne116=new  Sousligne();
        $sousligne117=new  Sousligne();
        $sousligne118=new  Sousligne();
        $sousligne119=new  Sousligne();
        $sousligne120=new  Sousligne();
        $sousligne121=new  Sousligne();
        $sousligne122=new  Sousligne();
        $sousligne123=new  Sousligne();
        $sousligne124=new  Sousligne();
        $sousligne125=new  Sousligne();
        $sousligne126=new  Sousligne();
        $sousligne127=new  Sousligne();
        $repository = $this->getDoctrine()->getRepository( Travail::class);
        $sousligne11->setTravail($repository->findBy(['id'=>'1'])[0]);$ligne11->addSousligne($sousligne11);
        $sousligne12->setTravail($repository->findBy(['id'=>'2'])[0]);$ligne11->addSousligne($sousligne12);
        $sousligne13->setTravail($repository->findBy(['id'=>'3'])[0]);$ligne11->addSousligne($sousligne13);
        $sousligne14->setTravail($repository->findBy(['id'=>'4'])[0]);$ligne11->addSousligne($sousligne14);
        $sousligne15->setTravail($repository->findBy(['id'=>'5'])[0]);$ligne11->addSousligne($sousligne15);
        $sousligne16->setTravail($repository->findBy(['id'=>'6'])[0]);$ligne11->addSousligne($sousligne16);

templates/administrateur/affecterenseignant.html.twig
<!Doctype html>
<html>
<head>

<title>{% block title %}Affecter Enseignant{% endblock %}</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
          div{
width: 500px;
margin: auto;
text-align: center;
border: 10px;
color: green;


}

        </style>
</head>
<body>
{% block body %}
<br><br>

<div>
    <h2>Affecter un enseignant à un {{eleve.Nom}} {{eleve.prenom}}</h2>

    {{ form_start(registrationForm) }}
    <br>

        
         {{ form_row(registrationForm.Enseignant) }}
     
    <br>
    <br>
     <button type="submit" class="btn btn-lg btn-primary">Enregistrer</button>
     </div>
     {{ form_end(registrationForm) }}
{% endblock %}
</body>
</html>

templates/administrateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AdministrateurController!{% endblock %}

{% block body %}
<style>
    wrapper { margin:  auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif;
display: grid;
  grid-template-columns: auto auto auto;
  background-color: #2196F3;
  padding: 10px;
 }
 .btn{
  border: 1px solid rgba(255, 255, 255, 0.8);
  padding: auto;
  font-size: 20px;
  text-align: center;
  margin:5%;
  text-decoration:none; 
  width: 20%;
  height: 150px;
 background-color: #0B4C5F;
 color: white;
 border-radius: 5%;
}
a {
    text-decoration:none; 
}

</style>

<div class="wrapper">
   <a href="/admin/listeadmin">
  <button type="button" class="btn">Administrateurs</button> </a>
   <a href="/admin/listeenseignants">
  <button type="button" class="btn">Enseignants</button> </a>
   <a href="/admin/listeeleves" >
  <button type="button" class="btn">Elèves</button>
   </a>
 <a href="">
  <button type="button" class="btn" >Consulter les archives</button> </a>
<a href="/admin/compte">
  <button type="button" class="btn" >Mon compte</button> </a>
<a href="/logout">
  <button type="button" class="btn" >Se déconnecter</button> </a>
</div>
{% endblock %}

templates/administrateur/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des {{type}}{% endblock %}


{% block body %}
<style>
td,th{
 border: solid 1px;
    
}
table{
    width: 80%;
}
a{
    text-decoration: none;
    color: black;
}
</style>
    <h1>Admin</h1>

    <table>
    <tr>
    <th>Id</th>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Adresse mail</th>
    </tr>
        {% for Admin in Admins %}
            <tr>
                <td><a href="">{{ Admin.id }}</a></td>
                <td><a href="">{{ Admin.nom }}</a></td>
                <td><a href="">{{ Admin.prenom }}</a></td>
                <td><a href="">{{ Admin.email }}</a></td>
                
            </tr>
    
    {% endfor %}
    </table>
    {% if type == 'Administrateurs'%}
    <a href="/admin/nouveladmin">
    <button type=button> Ajouter un {{type}}</button></a>
    {% else %}
    <a href="/admin/nouvelenseignant">
    <button type=button> Ajouter un {{type}}</button></a>
    {% endif %}
{% endblock %}

templates/administrateur/listeeleves.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des élèves{% endblock %}


{% block body %}
<style>
td,th,tr{
 border: solid 1px;
 text-allign: center;
}
table{
    width: 80%;
}
a{
    text-decoration: none;
    color: black;
}
button{
    background:rgb(36,255,255);
}
</style>
    <h1>Liste des élèves</h1>

    <table>
    <tr>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Classe</th>
    <th>Formation</th>
    <th>Spécialité</th>
    </tr>
        {% for Eleve in Eleves %}
            <tr>
                <td><a href="">{{ Eleve.nom }}</a></td>
                <td><a href="">{{ Eleve.prenom}}</a></td>
                <td><a href="">{{ Eleve.classe }}</a></td>
                <td><a href="">{{ Eleve.Formation }}</a></td>
                <td><a href="">{{ Eleve.specialite }}</a></td>
                <td><a href="/admin/{{Eleve.id}}/affecterenseignant"><button ">Affecter un enseignant</button></a></td>
                <td><a href=""><button >Faire passer en classe supérieure</button></a></td>
                
            </tr>
    
    {% endfor %}
    </table>
    <br><br>
     <a href="/admin/neweleveCAP"><button class="btn btn-lg btn-primary">Ajouter un nouvel Eleve</button></a>
{% endblock %}

templates/administrateur/moncompte.html.twig
{% extends 'base.html.twig' %}

{% block title %} Les informations de mon compte {% endblock %}


{% block body %}
<style>
td,th{
 border: solid 1px;
    
}
table{
    width: 80%;
}
a{
    text-decoration: none;
    color: black;
}
</style>
<br><br><br><br>
    <p> Nom: {{app.user.nom}}</p><br>
    <p> Prenom: {{app.user.prenom}}</p><br>
    <p> Adresse mail: {{app.user.email}}</p><br>
     <a href="/admin/{{app.user.id}}/changermdp"> <button class="btn btn-lg btn-primary">Changer mon mot de passe</button></a>
{% endblock %}

templates/administrateur/new.html.twig
<!Doctype html>
<html>
<head>

<title>{% block title %}Hello BienvenueController!{% endblock %}</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
          div{
width: 500px;
margin: auto;
text-align: center;
border: 10px;
color: green;


}

        </style>
</head>
<body>
{% block body %}
<br><br>

<div>
    <h2>Enregistrer un nouvel utilisateur</h2>

    {{ form_start(registrationForm) }}
    <br>
        
         {{ form_row(registrationForm.Nom) }}
         <br>
         {{ form_row(registrationForm.prenom) }}
         <br>
         {{ form_row(registrationForm.email) }}
         <br>
        {{ form_row(registrationForm.plainPassword, {
            label: 'Mot de passe'
        }) }}

       
    
    <br>
    <br>
     <button type="submit" class="btn btn-lg btn-primary">Enregistrer</button>
     </div>
     {{ form_end(registrationForm) }}
{% endblock %}
</body>
</html>

templates/administrateur/nouveleleve.html.twig
<!Doctype html>
<html>
<head>

<title>{% block title %}Hello BienvenueController!{% endblock %}</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
          div{
width: 500px;
margin: auto;
text-align: center;
border: 10px;
color: green;


}

        </style>
</head>
<body>
{% block body %}
<br><br>

<div>
    <h2>Enregistrer un nouvel Eleve</h2>

    {{ form_start(registrationForm) }}
    <br>

        
         {{ form_row(registrationForm.Nom) }}
         <br>
         {{ form_row(registrationForm.prenom) }}
         <br>
        
          {{ form_row(registrationForm.promotion) }}
         <br>
       {{ form_row(registrationForm.Formation) }}
         <br>
          {{ form_row(registrationForm.Specialite) }}
         <br>
          {{ form_row(registrationForm.classe) }}
         <br>
         

       

       
    
    <br>
    <br>
     <button type="submit" class="btn btn-lg btn-primary">Enregistrer</button>
     </div>
     {{ form_end(registrationForm) }}
{% endblock %}
</body>
</html>