src/Entity/Eleve.php
<?php

namespace App\Entity;

use App\Repository\EleveRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EleveRepository::class)
 */
class Eleve
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $prenom;


    /**
     * @ORM\Column(type="string", length=5)
     */
    private $promotion;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="ideleves")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Admin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tuteur;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $Specialite;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="eleves")
     */
    private $Enseignant;

    /**
     * @ORM\OneToMany(targetEntity=Cappfpmp::class, mappedBy="etudiant", cascade={"persist"})
     */
    private $cappfpmps;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $Classe;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Formation;

    public function __construct()
    {
        $this->cappfpmps = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getClasse(): ?string
    {
        return $this->Classe;
    }

    public function setClasse(string $classe): self
    {
        $this->Classe = $classe;

        return $this;
    }

    public function getPromotion(): ?string
    {
        return $this->promotion;
    }

    public function setPromotion(string $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    public function getAdmin(): ?utilisateur
    {
        return $this->Admin;
    }

    public function setAdmin(?utilisateur $Admin): self
    {
        $this->Admin = $Admin;

        return $this;
    }

    public function getTuteur(): ?string
    {
        return $this->tuteur;
    }

    public function setTuteur(string $tuteur): self
    {
        $this->tuteur = $tuteur;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->Specialite;
    }

    public function setSpecialite(?string $Specialite): self
    {
        $this->Specialite = $Specialite;

        return $this;
    }

    public function getFormation(): ?string
    {
        return $this->Formation;
    }

    public function setFormation(?string $Formation): self
    {
        $this->Formation = $Formation;

        return $this;
    }

    public function getEnseignant(): ?Utilisateur
    {
        return $this->Enseignant;
    }

    public function setEnseignant(?Utilisateur $Enseignant): self
    {
        $this->Enseignant = $Enseignant;

        return $this;
    }

    /**
     * @return Collection<int, Cappfpmp>
     */
    public function getCappfpmps(): Collection
    {
        return $this->cappfpmps;
    }

    public function addCappfpmp(Cappfpmp $cappfpmp): self
    {
        if (!$this->cappfpmps->contains($cappfpmp)) {
            $this->cappfpmps[] = $cappfpmp;
            $cappfpmp->setEtudiant($this);
        }

        return $this;
    }

    public function removeCappfpmp(Cappfpmp $cappfpmp): self
    {
        if ($this->cappfpmps->removeElement($cappfpmp)) {
            // set the owning side to null (unless already changed)
            if ($cappfpmp->getEtudiant() === $this) {
                $cappfpmp->setEtudiant(null);
            }
        }

        return $this;
    }

    
}

src/Controller/EnseignantsController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Entity\Eleve;
use App\Entity\Cappfpmp;
use App\Form\SousligneType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;


class EnseignantsController extends AbstractController
{
    /**
     * @Route("/enseignants", name="app_Enseignant")
     */
    public function index(): Response
    
    {
      
        return $this->render('enseignants/index.html.twig', [
            'controller_name' => 'PageEnseignant',
        ]);
    }
     /**
     * @Route("/enseignants/listeeleves", name="elevesliste")
     */
    public function liste(): Response
    
    {
      
        return $this->render('enseignants/liste.html.twig', [
            'controller_name' => 'PageEnseignant',
        ]);
    }
      /**
     * @Route("/enseignants/noterelevecap/{id}", name="notereleve")
     */
    public function noter(ELeve $eleve): Response
    
    {
      $pfpmp1=$eleve->getCappfpmps()[0];
      $pfpmp2=$eleve->getCappfpmps()[1];
      $pfpmp3=$eleve->getCappfpmps()[2];
      $pfpmp4=$eleve->getCappfpmps()[3];
        return $this->render('enseignants/choixpfmpnotecap.html.twig', [
            'controller_name' => 'PageEnseignant',
            'pfpmp1' => $pfpmp1,
            'pfpmp2' => $pfpmp2,
            'pfpmp3' => $pfpmp3,
            'pfpmp4' => $pfpmp4
            
        ]);
    }
   /**
     * @Route("/enseignant/{id}/noterpfpmp", name="noterpfmp")
     */
    public function evaluercap(Cappfpmp $pfmp, Request $request,EntityManagerInterface $entityManager): Response
    
    {dump($request);
        if($request->request->count()>0)
        {foreach($pfmp->getLignes() as $Lignes )
            {foreach($Lignes->getSousligne() as $sousligne)
                {
                    $sousligne->setNote($request->request->get($sousligne->getTravail()->getLibelle()));
                    $entityManager->persist($sousligne);
            $entityManager->flush();
                }
             }
            
        }
        

        return $this->render('enseignants/evalcappfmp.html.twig', [
            'PFMP'  =>$pfmp]);

    }
}

templates/enseignants/choixpfmpnotecap.html.twig
{% extends 'base.html.twig' %}

{% block title %}Noter eleve{% endblock %}

{% block body %}
<style>
    wrapper { margin:  auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif;
display: grid;
  grid-template-columns: auto auto auto;
  background-color: #2196F3;
  padding: 10px;
 }
 .btn{
  border: 1px solid rgba(255, 255, 255, 0.8);
  padding: 5%;
  font-size: 30px;
  text-align: center;
  margin:50px;
  text-decoration:none; 
  min-width: 40%;
  min-height: 50%;
 background-color: #0B4C5F;
 color: white;
 border-radius: 5%;
}
a {
    text-decoration:none; 
}

</style>

<div class="wrapper">
   <a href="/enseignant/{{pfpmp1.id}}/noterpfpmp">
  <button type="button" class="btn">PFPM1</button> </a>
   <a href="/enseignant/{{pfpmp2.id}}/noterpfpmp">
    <button type="button" class="btn">PFPM2</button> </a>
   <a href="/enseignant/{{pfpmp3.id}}/noterpfpmp">
  <button type="button" class="btn">PFPM3</button> </a>
   <a href="/enseignant/{{pfpmp4.id}}/noterpfpmp">
     <button type="button" class="btn">PFPM4</button> </a>
  
</div>
{% endblock %}

templates/enseignants/evalcappfmp.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BienvenueController!{% endblock %}
{% block head%}
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
          div{
margin: auto;
text-align: center;
background-color:0B4C5F;
border: 10px;
color: green;
}
 td,tr,table{
    margin:auto;

    padding: 4px;
    border: solid 1px;
 text-allign: center;
}

        </style>
</head>
{% endblock %}

{% block body %}
<br><br>

<div>
    <h2>Evaluer le PFPM n°{{ PFMP.numero}} de {{PFMP.etudiant.nom}}</h2>

    <form action="" method="POST">
    <br>
      <table>
        {% for Ligne in PFMP.lignes%}
        <tr><h5> {{Ligne.competence.libelle}}</h5></tr>
        
        <tr><h6>Travaux demandés</h6>
        <table>
        {% for sousligne in Ligne.sousligne%}

         <tr><td> {{sousligne.travail.libelle}}:</td><td><p>   </p><input type="text" name="{{sousligne.travail.libelle}}" placeholder="Maitrise"></td></tr>
        {%endfor%}
        </table>
        <tr>
        {%endfor%}
        </table>
        <br>
     <button type="submit" class="btn btn-lg btn-primary">Enregistrer</button>
     </form>
     <br>
     <br>
     <br>
     </div>
{% endblock %}

templates/enseignants/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AdministrateurController!{% endblock %}

{% block body %}
<style>
    wrapper { margin:  auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif;
display: grid;
  grid-template-columns: auto auto auto;
  background-color: #2196F3;
  padding: 10px;
 }
 .btn{
  border: 1px solid rgba(255, 255, 255, 0.8);
  padding: 5%;
  font-size: 30px;
  text-align: center;
  margin:50px;
  text-decoration:none; 
  min-width: 40%;
  min-height: 50%;
 background-color: #0B4C5F;
 color: white;
 border-radius: 5%;
}
a {
    text-decoration:none; 
}

</style>

<div class="wrapper">
   <a href="/admin/listeadmin">
  <button type="button" class="btn">Mes élèves</button> </a>
   <a href="/admin/listeenseignants">
  <button type="button" class="btn">Mon compte</button> </a>
<a href="">
  <button type="button" class="btn" >Se déconnecter</button> </a>
  <a href="">
  <button type="button" class="btn" >Noter un élève</button> </a>
</div>
{% endblock %}

templates/enseignants/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste de mes élèves{% endblock %}


{% block body %}
<style>
td,th{
 border: solid 1px;
    
}
table{
    width: 80%;
}
a{
    text-decoration: none;
    color: black;
}
</style>
    <h1>Admin</h1>

    <table>
    <tr>
    <th>Id</th>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Classe</th>
    </tr>
        {% for Admin in app.user.eleves %}
            <tr>
                <td><a href="">{{ Admin.id }}</a></td>
                <td><a href="">{{ Admin.nom }}</a></td>
                <td><a href="">{{ Admin.prenom }}</a></td>
                <td><a href="">{{ Admin.classe }}</a></td>
                <td><a href="">{{ Admin.formation}}</a></td>
                <td><a href="/enseignants/noterelevecap/{{Admin.id}}"><button class="btn btn-lg btn-primary">Noter</button></a></td>
                
            </tr>
    
    {% endfor %}
    </table>
{% endblock %}

templates/enseignants/new.html.twig
<title>{% block title %}Hello BienvenueController!{% endblock %}</title>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
          div{
width: 500px;
margin: auto;
text-align: center;
background-color:0B4C5F;
border: 10px;
color: green;


}

        </style>
</head>
<body>
{% block body %}
<br><br>

<div>
    <h2>Enregistrer un nouvel Enseignants</h2>

    {{ form_start(registrationForm) }}
    <br>
        
         {{ form_row(registrationForm.Nom) }}
         <br>
         {{ form_row(registrationForm.prenom) }}
         <br>
         {{ form_row(registrationForm.email) }}
         <br>
        {{ form_row(registrationForm.plainPassword, {
            label: 'Mot de passe'
        }) }}

       
    
    <br>
    <br>
     <button type="submit" class="btn btn-lg btn-primary">Enregistrer</button>
     </div>
     {{ form_end(registrationForm) }}
{% endblock %}
</body>
</html>